name: Context variables demo
on: push
jobs:
  context-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Use context variables
        run: |
          echo "This workflow is triggered by ${{ github.actor }}"
          echo "The repository name is ${{ github.repository }}"
          echo "The branch is ${{ github.ref_name }}"
  
      - name: Print all variables under github
        run:  echo "${{  toJson(github) }}"
