name: Env Demo
on: workflow_dispatch
env:
  APP_ENV: "dev"
jobs:
  env_demo:
    runs-on: ubuntu-latest
    steps:
      - name: Connecting to env:
        run: echo "App is connecting to $APP_ENV"
        
